name: backend-minut

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-minut
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sysdev@2025
      POSTGRES_DB: bridging_asuransi_minut
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Untuk restore backup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: backend-minut
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    ports:
      - "0.0.0.0:3005:3000"  # Bind to all interfaces
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
